
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-12
owner: ucsb-cs156-f25
repo_name: team02-f25-12
pull_requests: [{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-index-page-help","number":112,"title":"Hrehwald index page help","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/112"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-menuitemreview-placeholder2","number":111,"title":"AlvinC - Placeholders for MenuItemReview (REDO)","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/111"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-edit-helprequest","number":110,"title":"Hrehwald edit helprequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/110"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-editPage-helprequests","number":108,"title":"Hrehwald edit page helprequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/108"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-create-page-Helprequests","number":106,"title":"Hrehwald create page helprequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/106"}]
