
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-12
owner: ucsb-cs156-f25
repo_name: team02-f25-12
pull_requests: [{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-end2end-help","number":140,"title":"Hrehwald end2end help","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/140"},{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-team03end2end","number":139,"title":" tst - added the end to end tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/139"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-testing","number":138,"title":"hrehwald integration tests helprequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/138"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-menuitemreview-team03end","number":127,"title":"AlvinC - End2End tests for  MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/127"},{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-articles-e2e-tests","number":126,"title":"Bj articles e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/126"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-menuitemreview-team03","number":125,"title":"AlvinC - add integration tests for MenuItemReview Controller Endpoints","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/125"}]
