
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-12
owner: ucsb-cs156-f25
repo_name: team02-f25-12
pull_requests: [{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-form","number":77,"title":"Ja form","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/77"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-menuitemreview-plustests","number":76,"title":"alvinc - added MenuItemReview Form Plus Tests for frontend. ","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/76"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"21-copy-placeholders-for-ucsborganization-pages-add-to-appjsappnavbarjs","number":75,"title":"added filler ucsborg pages and links","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/75"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-fixtures","number":74,"title":"Ja fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/74"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"19-form-component-for-ucsborganization-plus-tests","number":70,"title":"created org form and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/70"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-crud","number":69,"title":"copying backend for CRUD operations from team01","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/69"}]
