
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-12
owner: ucsb-cs156-f25
repo_name: team02-f25-12
pull_requests: [{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-e2e","number":142,"title":"Ja e2e","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/142"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-integration-tests","number":141,"title":"adding integration tests for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team02-f25-12/pull/141"}]
